# Generated by Django 4.1.6 on 2023-02-18 22:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountNumber',
            fields=[
                ('number', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('entry_date', models.DateField(default=datetime.datetime(2023, 2, 18, 22, 1, 2, 195394, tzinfo=datetime.timezone.utc))),
                ('account_balance', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=18)),
            ],
        ),
        migrations.CreateModel(
            name='BookManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=12)),
                ('password', models.CharField(max_length=18)),
                ('phone', models.CharField(max_length=12)),
                ('is_main', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=12)),
                ('phone', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Creditor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.accountnumber')),
            ],
        ),
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum', models.IntegerField()),
                ('date_signed', models.DateField()),
                ('date_due', models.DateField()),
                ('creditor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.creditor')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('passportNumber', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=18)),
                ('surname', models.CharField(max_length=15)),
                ('client_number', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.accountnumber')),
            ],
        ),
    ]
