# Generated by Django 4.1.6 on 2023-02-18 22:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountnumber',
            name='entry_date',
            field=models.DateField(default=datetime.datetime(2023, 2, 18, 22, 1, 22, 877010, tzinfo=datetime.timezone.utc)),
        ),
    ]
