# Generated by Django 4.1.6 on 2023-02-19 17:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_accountnumber_entry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmanager',
            name='client',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.client'),
        ),
        migrations.AddField(
            model_name='director',
            name='book_manager',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.bookmanager'),
        ),
        migrations.AlterField(
            model_name='accountnumber',
            name='entry_date',
            field=models.DateField(default=datetime.datetime(2023, 2, 19, 17, 55, 7, 884887, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='credit',
            name='creditor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.creditor'),
        ),
    ]
